#
# Build a simple website
# Deepak Shenoy
# May 1st, 2026
#

from aws_cdk import (
    # Duration,
    Stack,
    # aws_sqs as sqs,
    aws_s3 as s3,
    CfnOutput,
)

from constructs import Construct

class WebsiteTemplatePyStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # The code that defines your stack goes here

        # example resource
        # queue = sqs.Queue(
        #     self, "WebsiteTemplatePyQueue",
        #     visibility_timeout=Duration.seconds(300),
        # )

        #
        # Create a S3 bucket to store the website static content
        # use autogenerated KMS key
        #
        content_bucket = s3.Bucket(self, "sitecontent-shenoy",
                                   encryption=s3.BucketEncryption.KMS,
                                   website_index_document="index.html",
                                   website_error_document="error.html",
                                   public_read_access=True,
                                   block_public_access=s3.BlockPublicAccess.BLOCK_ACLS,
                                   removal_policy=s3.RemovalPolicy.DESTROY,   # Delete bucket on cdk destroy
                                   auto_delete_objects=True,                  # Empties bucket before deleting
                                   )

        CfnOutput(self, "WebsiteURL",
                  value=content_bucket.bucket_website_url,
                  description="Static website URL")
